### ISSUE TITLE
Proposal to add "Detailed reading mode"

### ISSUE THREAD

**Issue by murata2makoto** [w3c/i18n-glossary#13]
The Japanese language has many homonyms.  For example, IPA phonetics (i／koː‾) can be interpreted in at least six ways:

- 遺稿 posthumous manuscripts
- 意向 intention; purpose; intent; inclination; disposition
- 移行 move, change over
- 移項 (intransitive, algebra) to transpose terms
- 遺構 remains
- 威光 authority or prestige

It is not always possible to choose one of the possible homonyms from the context.  To overcome this problem, some made-in-Japan screen readers provide a special mode called the detailed reading (詳細読み).

In the detailed reading mode, each CJK ideographic is read aloud separately.  In other words, words containing CJK ideographic characters are NOT read aloud as such. Moreover, each CJK ideographic character is read aloud together with a commonly-used word containing it.  As an example, consider the word 意向 ("intention"), which is one of the six words lited above.  It is not read aloud as (i／koː‾).  Rather, 意 is read aloud together with a commonly-used word 意見 ("opinion") and then 向 is read aloud together with 向上 ("progress").  The detailed reading mode thus precisely specifies CJK ideographic characters.  (Note: a variation of the detailed reading mode explains each CJK ideographic character in terms of its radicals.)

Unfortunately, as far as I know, none of the EPUB readers or browser engines provide the detailed reading mode.

**Comment by t-kudou** [comment]
> In the detailed reading mode, each CJK ideographic is read aloud separately. 

I think the explanation that each kanji character is read out is insufficient. And should be supplemented with an explanation that "the kanji is presented in detail so that the reader can determine what kind of kanji it is.
How about modifying this part as follows.

In the detailed reading, each CJK ideograph is presented in such a way that the reader can determine what kind of kanji is used for each character.

Also, although the entire description is based on the assumption that the text is read out, I thought it would be better to use  'present' since read alone would be a biased description since detailed reading is also used when reading text information in Braille on a Braille terminal.
How about to change issued glossary name to 'Detailed presentation mode'?

**Comment by murata2makoto** [comment]
@t-kudou 

>In the detailed reading, each CJK ideograph is presented in such a way that the reader can determine what kind of kanji is used for each character.

I wrote "Moreover, each CJK ideographic character is read aloud together with a commonly-used word containing it. "  Is this sufficient?

>How about to change issued glossary name to 'Detailed presentation mode'?

I agree that "reading" does not cover braille rendering.  How about "Detailed rendering mode"?

**Comment by xfq** [comment]
I think the i18n glossary is mainly for explaining terms that are already in other documents and standards. Any document that needs to refer to this term?

**Comment by aphillips** [comment]
discussed in tpac 2024-09-23. consider adding to jlreq
