### ISSUE TITLE
About Tashkil : long vowel marks are called Madd.

### ISSUE THREAD

**Issue by ntounsi** [w3c/i18n-glossary#51]
https://www.w3.org/TR/i18n-glossary/#dfn-tashkil
"These include several subtypes: harakat (short vowel marks), _tanwin (postnasalized or long vowel marks)_, shaddah (consonant gemination mark), and sukun (to mark lack of a following vowel)."

1) s/tanwin (postnasalized or long vowel marks)/tanwin (postnasalized, i.e. extra NOON sound at the end of a noun and marked by double harakat.)
See e.g. https://en.al-dirassa.com/tanween-double-vowel-marks-lesson-3/

2) "Long vowel mark" is called "Madd" (literally extension, prologation) and is marked by Alef for long A, Waw for long U  or Yeh for long I
See e.g. https://en.al-dirassa.com/the-long-vowel-marks-arabic-free-course-lesson-4/

May be add "Madd" to your list of subtypes of tashkil (harakat..., tanwin..., madd..., shaddah..., sukun...?

**Comment by aphillips** [comment]
@r12a This sounds good to me. Are there other places where this would be picked up?

**Comment by r12a** [comment]
The first redefinition (tanwin) seems ok, but we should replace 'extra NOON sound' with 'extra /n/ sound' (using appropriate markup for the IPA). I agree that talking about a double harakat makes more sense than saying 'long vowel mark'.  (I think potnasalised and long both qualify 'vowel marks', though that's not clear in the original.)

The second redefinition (madd) seems a little more problematic to me, because many people will know the word madd from آ U+0622: ARABIC LETTER ALEF WITH MADDA ABOVE, where the madd refers to the diacritic which is actually a hamza (not tashkil) above a long vowel (aleph).  I'm not sure whether that will cause confusion for some people.  Note also that we tend to refer to the long a, i, u vowels as matres lectionis, rather than using the arabic word madd, but 'long vowel' is in my opinion a better way to describe them for english speakers.

**Comment by r12a** [comment]
I think we should edit the glossary to use Najib's definition of tanwin, substituting /n/ for NOON.

I propose NOT to include the definition of madd, since this is a definition for tashkil, and because the entry is already long enough and is in danger of turning into a tutorial, rather than a definition;

**Comment by ntounsi** [comment]
For tanwin, may be replace “double harakat” with “double similar harakat”.
Close ?

**Comment by aphillips** [comment]
@ntounsi I made the change. Please see the pull request [here](https://github.com/w3c/i18n-glossary/pull/75).
